{
    "name": "Omarchy",
    "author": "Omarchy",
    "variables": {
        "background": "{{ background }}",
        "foreground": "{{ foreground }}",
        "accent": "{{ accent }}",
        "selection": "{{ selection }}",
        "muted": "{{ muted }}",
        "red": "{{ red }}",
        "orange": "{{ orange }}",
        "yellow": "{{ yellow }}",
        "green": "{{ green }}",
        "cyan": "{{ cyan }}",
        "blue": "{{ blue }}",
        "magenta": "{{ magenta }}"
    },
    "globals": {
        "background": "var(background)",
        "foreground": "var(foreground)",
        "caret": "var(accent)",
        "block_caret": "var(accent)",
        "invisibles": "var(muted)",
        "line_highlight": "{{ lighter_background }}",
        "selection": "var(selection)",
        "selection_border": "var(selection)",
        "inactive_selection": "{{ lighter_background }}",
        "misspelling": "var(red)",
        "shadow": "{{ darker_background }}",
        "active_guide": "var(muted)",
        "stack_guide": "{{ lighter_background }}",
        "guide": "{{ lighter_background }}",
        "gutter": "var(background)",
        "gutter_foreground": "var(muted)",
        "gutter_foreground_highlight": "var(foreground)",
        "highlight": "var(accent)",
        "find_highlight": "var(yellow)",
        "find_highlight_foreground": "var(background)",
        "brackets_options": "underline",
        "brackets_foreground": "var(accent)",
        "bracket_contents_options": "underline",
        "bracket_contents_foreground": "var(accent)",
        "tags_options": "stippled_underline",
        "tags_foreground": "var(accent)",
        "line_diff_added": "var(green)",
        "line_diff_modified": "var(yellow)",
        "line_diff_deleted": "var(red)"
    },
    "rules": [
        { "name": "Comment", "scope": "comment, punctuation.definition.comment", "foreground": "var(muted)", "font_style": "italic" },
        { "name": "String", "scope": "string, meta.string", "foreground": "var(green)" },
        { "name": "Escape", "scope": "constant.character.escape, string.regexp", "foreground": "var(cyan)" },
        { "name": "Number", "scope": "constant.numeric, constant.language, constant.other", "foreground": "var(orange)" },
        { "name": "Keyword", "scope": "keyword, storage.type, storage.modifier", "foreground": "var(magenta)" },
        { "name": "Operator", "scope": "keyword.operator, punctuation.accessor, punctuation.separator", "foreground": "var(cyan)" },
        { "name": "Punctuation", "scope": "punctuation.section, punctuation.terminator, punctuation.definition.block", "foreground": "var(foreground)" },
        { "name": "Function", "scope": "entity.name.function, support.function, variable.function, meta.function-call", "foreground": "var(blue)" },
        { "name": "Type", "scope": "entity.name.type, entity.name.class, entity.other.inherited-class, support.type, support.class, storage.type.class", "foreground": "var(yellow)" },
        { "name": "Variable", "scope": "variable, variable.other", "foreground": "var(foreground)" },
        { "name": "Parameter", "scope": "variable.parameter", "foreground": "var(red)" },
        { "name": "Language variable", "scope": "variable.language", "foreground": "var(red)", "font_style": "italic" },
        { "name": "Property", "scope": "variable.other.member, variable.other.property, meta.property-name, support.type.property-name", "foreground": "var(cyan)" },
        { "name": "Tag", "scope": "entity.name.tag", "foreground": "var(blue)" },
        { "name": "Attribute", "scope": "entity.other.attribute-name", "foreground": "var(yellow)" },
        { "name": "Markup heading", "scope": "markup.heading, markup.heading entity.name", "foreground": "var(accent)", "font_style": "bold" },
        { "name": "Markup bold", "scope": "markup.bold", "font_style": "bold" },
        { "name": "Markup italic", "scope": "markup.italic", "font_style": "italic" },
        { "name": "Markup link", "scope": "markup.underline.link", "foreground": "var(blue)" },
        { "name": "Markup code", "scope": "markup.raw", "foreground": "var(green)" },
        { "name": "Inserted", "scope": "markup.inserted", "foreground": "var(green)" },
        { "name": "Changed", "scope": "markup.changed", "foreground": "var(yellow)" },
        { "name": "Deleted", "scope": "markup.deleted", "foreground": "var(red)" },
        { "name": "Invalid", "scope": "invalid", "foreground": "var(red)" }
    ]
}
